### ISSUE TITLE
使用 create-molecule 创建应用失败

### ISSUE THREAD

**Issue by wewoor** [DTStack/create-molecule#1]
> yarn 版本：1.22.19
> node 版本：v16.15.1
> registry: https://yarnpkg.com/

完整的日志：

```
0 verbose cli /Users/ziv/.nvm/versions/node/v16.15.1/bin/node /Users/ziv/.nvm/versions/node/v16.15.1/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.11.0
2 info using node@v16.15.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/Users/ziv/.nvm/versions/node/v16.15.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 4ms
10 timing config:load:file:/Users/ziv/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/Users/ziv/.nvm/versions/node/v16.15.1/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 2ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 18ms
18 timing npm:load:configload Completed in 19ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm exec create-react-app molecule-fluentui-admin
22 verbose argv "exec" "--" "create-react-app" "molecule-fluentui-admin"
23 timing npm:load:setTitle Completed in 20ms
24 timing config:load:flatten Completed in 2ms
25 timing npm:load:display Completed in 4ms
26 verbose logfile logs-max:10 dir:/Users/ziv/.npm/_logs
27 verbose logfile /Users/ziv/.npm/_logs/2022-07-21T03_03_37_992Z-debug-0.log
28 timing npm:load:logFile Completed in 21ms
29 timing npm:load:timers Completed in 1ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 66ms
32 silly logfile start cleaning logs, removing 2 files
33 timing arborist:ctor Completed in 1ms
34 silly logfile done cleaning log files
35 http fetch GET 404 https://yarnpkg.com/create-react-app 1010ms (cache skip)
36 http fetch GET 404 https://yarnpkg.com/create-react-app 311ms (cache skip)
37 timing command:exec Completed in 1571ms
38 verbose stack HttpErrorGeneral: 404 Not Found - GET https://yarnpkg.com/create-react-app
38 verbose stack     at /Users/ziv/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:93:15
38 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
38 verbose stack     at async RegistryFetcher.packument (/Users/ziv/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:92:19)
38 verbose stack     at async RegistryFetcher.manifest (/Users/ziv/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:124:23)
38 verbose stack     at async /Users/ziv/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:128:12
38 verbose stack     at async Promise.all (index 0)
38 verbose stack     at async exec (/Users/ziv/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:114:17)
38 verbose stack     at async module.exports (/Users/ziv/.nvm/versions/node/v16.15.1/lib/node_modules/npm/lib/cli.js:78:5)
39 verbose statusCode 404
40 verbose pkgid create-react-app@latest
41 verbose cwd /Users/ziv/Workspace
42 verbose Darwin 21.5.0
43 verbose node v16.15.1
44 verbose npm  v8.11.0
45 error code E404
46 error 404 Not Found - GET https://yarnpkg.com/create-react-app
47 error 404
48 error 404  'create-react-app@latest' is not in this registry.
49 error 404
49 error 404 Note that you can also install from a
50 error 404 tarball, folder, http url, or git url.
51 verbose exit 1
52 timing npm Completed in 1862ms
53 verbose code 1
54 error A complete log of this run can be found in:
54 error     /Users/ziv/.npm/_logs/2022-07-21T03_03_37_992Z-debug-0.log
```

**Comment by mortalYoung** [comment]
你的 registry 不对吧

```shell
➜  $ yarn config get registry
https://registry.npm.taobao.org/
```

**Comment by wewoor** [comment]
> 你的 registry 不对吧
> 
> ```shell
> ➜  $ yarn config get registry
> https://registry.npm.taobao.org/
> ```

切换到
> https://registry.yarnpkg.com/
源就好了
